### PR TITLE
feat(cmd): add pnp_csv in export command

### LINKED ISSUE #182: Support `tsci export pnp-csv --input path/to/example.tsx`
Should do the same thing as when you hit "File > Export -> Pick'n'Place CSV" from the file menu, but be available from the command line

image

### PR DESCRIPTION
**Pull request by qalbun-salim**
## Summary
- Add `export pnp_csv` in command line
- Add unit tests for `pnp_csv` command

## Related Issue
Closes #182

### CODE REVIEW

**Comment by qalbun-salim** [comment]
Hi! This is my first PR for hacktoberfest, please kindly review 🙏 

Would also like your help to add `hacktoberfest-accepted` label in the PR or `hacktoberfest` label in the repo to be counted as a contribution according to [this](https://hacktoberfest.com/participation/) guideline.
Thank you in advance! 🙇

**Comment by imrishabh18** [comment]
@qalbun-salim Looks good.But can you add the screen recording or the screen shot of this please? It would be helpful to review.

**Comment by imrishabh18** [comment]
Regarding the hacktoberfest, this repository is already having the `hacktoberfest` label. So, I think it will be counted towards it

**Comment by qalbun-salim** [comment]
HI, sorry for the late repl
Below is attached recording for the example, thanks!

https://github.com/user-attachments/assets/b2a097fc-1efa-4fda-9396-563348a4d1eb

**Comment by imrishabh18** [comment]
@qalbun-salim Looks great! Can you please fix the formatting issue? It would be good to merge after that

**Comment by qalbun-salim** [comment]
Please kindly rereview @imrishabh18  🙏

**Comment by imrishabh18** [comment]
Thanks for the contribution! @qalbun-salim

**Pull request merged**
