### PR TITLE
feat: new `render` image command added

### PR DESCRIPTION
**Pull request by imrishabh18**
Closes - #112

https://github.com/user-attachments/assets/f3d2e141-588b-475d-836b-5fceae3f9d35

### CODE REVIEW

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
This is sweet

**Comment by imrishabh18** [comment]
The pcb worked fine, but the schematic in the circuit-to-png needs some work for parsing some fields I think

**Comment by seveibar** [comment]
@imrishabh18 make sure not to merge on red ci checks, the package won't release until they're fixed (I'm going to fix these ones because I want to do some refactoring anyway)

**Comment by imrishabh18** [comment]
Oh okay, these tests are failing for all the PR's. So, I just merged it

**Pull request merged**
